spring:
  logging:
    level:
      ROOT: DEBUG
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: saleh2910
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 15
      maximum-pool-size: 25
  jpa:
   # show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  application:
    security:
      jwt:
        secret-key: 5166546A576E5A7234753778217A25432A462D4A614E645267556B5870327335
        expiration: 864000000000 # one minute
        refresh-token:
          expiration: 60480000000000  # two minute
  liquibase:
    enabled: true
    changeLog: classpath:/liquibase/Product_Management.xml
    dropFirst: false
    databaseChangeLogLockTable: PRODUCT_MANAGEMENT_CHANGELOG_LOCK
    databaseChangeLogTable: PRODUCT_MANAGEMENT_CHANGELOG
    defaultSchema: public
  mvc:
    dispatchOptionsRequest: true
    cors:
      enabled: true
      allowed-origins:
        - http://173.212.239.87:6464
      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
      allowed-headers:
        - "*"
      allow-credentials: true
server:
  port: 8080
  servlet:
   context-path: /property

# config.yml
credentials:
  username: user4ab
  password: Ck0!6AVH27sh!
  title: SMS TEST



